name: beeto_ai
description: An AI Assistant (ChatBot, Image Generator & Language Translator) App Based on ChatGPT developed by Harsh H. Rajpurohit 

publish_to: 'none' 

# App Version
version: 1.0.2+2

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Google Gemini Ai Integration
  google_generative_ai: ^0.4.3

  # For using Lottie Animations
  lottie: ^3.1.2

  # For State Management
  get: ^4.6.6

  # For Custom Animation
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2

  # For API Call
  http: ^1.2.2

  # For Google Language Translate
  translator_plus: ^1.0.1

  # For Saving Image to Gallery
  image_gallery_saver: ^2.0.3

  # For Loading Environment Variables
  flutter_dotenv: ^5.2.1
  
  # For using Icons
  iconsax: ^0.0.8

  # For using fast storage
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Encourages Good Practices
  flutter_lints: ^4.0.0


flutter:

  # Enables Material Design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
